version: '3.3'

services:
 base-api:
  build: .
  image: todo-api
  ports:
  - 5000:5000

 mysql-api:
  build:
   context: .
   dockerfile: mysql.Dockerfile
  ports:
  - 5001:5000
  volumes:
  - ./:/app
  depends_on:
   - base-api
   - mysqldb
  environment:
   TODO_LIST_DB_IMPLEMENTATION: todo_list_api_mysql.db.TodoListMySQL
   MYSQL_PASSWORD: p@ssw0rd1  # should be done with some secret
   MYSQL_USER: root
   MYSQL_HOST: mysql
   MYSQL_DATABASE: todo

 dynamodb-api:
  build:
   context: .
   dockerfile: dynamodb.Dockerfile
  ports:
   - 5002:5000
  environment:
   TODO_LIST_DB_IMPLEMENTATION: todo_list_api_dynamo.db.TodoListDynamoDB
   DYNAMODB_TABLE: todo-list-table
   DYNAMODB_REGION: eu-west-1
   DYNAMODB_ENDPOINT: http://localstack:4566
   AWS_ACCESS_KEY_ID: foo
   AWS_SECRET_ACCESS_KEY: bar
  depends_on:
  - localstack

 mysqldb:
  container_name: "mysql"
  image: mysql:8.0.26
  ports:
  - 3306:3306
  environment:
  - MYSQL_ROOT_PASSWORD=p@ssw0rd1
  volumes:
  - mysql:/var/lib/mysql
  - mysql_config:/etc/mysql

 localstack:
   container_name: "localstack"
   image: "localstack/localstack:0.12.6"
   ports:
     - "4566:4566"
   environment:
     - SERVICES=dynamodb
volumes:
  mysql:
  mysql_config: